services:
  elasticsearch:
    image: "elasticsearch:8.13.0"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - musicStack
  music-backend:
    image: "music-backend:latest"
    environment:
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
    networks:
      - musicStack

networks:
  musicStack:
    driver: bridge