services:
  elasticsearch:
    image: "elasticsearch:8.13.0"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - musicStack
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
        ]
      interval: 2s
      timeout: 10s
      retries: 24
  music-backend:
    image: "music-backend:latest"
    environment:
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200
    ports:
      - 8080:8080
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - musicStack

networks:
  musicStack:
    driver: bridge